name: lanaexpress
description: "A client for LanaExpress service"
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.14+10014

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.16.9

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  gap: ^3.0.1
  stacked: ^3.4.1+1
  stacked_hooks: ^0.2.3
  stacked_services: ^1.3.0
  translator: ^0.1.7
  logger: ^2.0.2+1
  win32: ^5.8.0
  #firebase_crashlytics: ^3.4.13
  auto_route: ^7.8.4
  provider: ^6.1.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  fluttertoast: ^8.2.4
  file_picker: ^6.1.1

  #network
  dio: ^5.4.1
  pretty_dio_logger: ^1.1.1
  retry: ^3.1.2

  # local storage / cache
  shared_preferences: ^2.2.2
  # flutter_cache_manager: ^3.3.1
  # cached_network_image: ^3.3.1

  connectivity: ^3.0.6
  responsive_builder: ^0.7.0
  stacked_themes: ^0.3.12
  get: ^4.6.6
  get_it: ^7.6.7
  injectable: ^2.3.2
  l: ^4.0.0
  intl: ^0.19.0
  google_maps_flutter: ^2.5.3
  geolocator: ^13.0.0
  geocoding: ^2.2.1
  flutter_polyline_points: ^1.0.0
  google_places_flutter: ^2.0.9
  uuid: ^4.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_pdfview: ^1.2.5
  path_provider: ^2.1.3
  mime: ^1.0.5
  mime_type: ^1.0.0
  flutter_image_compress: ^2.3.0
  multi_dropdown: ^2.1.4
  flutter_local_notifications: ^17.2.1+2
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  flutter_background_service_ios: ^5.0.3
  #device_info_plus: ^9.1.2
  flutter_secure_storage: ^9.2.2
  maps_toolkit: ^3.0.0
  android_intent_plus: ^5.1.0
  google_maps_routes: ^1.1.2
  url_launcher: ^6.3.0
  pusher_channels_flutter: ^2.2.1
  audioplayers: ^6.1.0

dependency_overrides:
  photo_manager: ^3.0.0-dev.5
  wechat_assets_picker: ^9.0.0-dev.2
  http: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png" 
  image_path_android: "assets/icons/app_icon.png" 
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/placeholders/
    - assets/sounds/mixkit-retro-game-notification-212.wav

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
